export const skillsData = [
  {
    Category: "Programming Languages",
    Skills: [
      "Java",
      "Python",
      "C++",
      "JavaScript",
      "Ruby",
      "Swift",
      "Go",
      "PHP",
      "C#",
      "Kotlin",
    ],
  },
  {
    Category: "Web Development",
    Skills: [
      "HTML",
      "CSS",
      "React",
      "Angular",
      "Vue.js",
      "Node.js",
      "Express.js",
      "Django",
      "Flask",
      "ASP.NET",
    ],
  },
  {
    Category: "Database Management",
    Skills: [
      "SQL",
      "MySQL",
      "PostgreSQL",
      "MongoDB",
      "SQLite",
      "Oracle DB",
      "Firebase",
      "Cassandra",
      "Redis",
      "DynamoDB",
    ],
  },
  {
    Category: "Frameworks & Libraries",
    Skills: [
      "Spring Boot",
      "Ruby on Rails",
      "jQuery",
      "Bootstrap",
      "Redux",
      "Hibernate",
      "TensorFlow",
      "PyTorch",
      "Flask-SQLAlchemy",
      "Laravel",
    ],
  },
  {
    Category: "Version Control",
    Skills: [
      "Git",
      "SVN",
      "Mercurial",
      "Perforce",
      "TFS",
      "CVS",
      "Bazaar",
      "Darcs",
      "Fossil",
      "Plastic SCM",
    ],
  },
  {
    Category: "Mobile App Development",
    Skills: [
      "React Native",
      "Flutter",
      "iOS SDK",
      "Android SDK",
      "Swift",
      "Kotlin",
      "Xamarin",
      "PhoneGap",
      "Ionic",
      "Cordova",
    ],
  },
  {
    Category: "Testing & Debugging",
    Skills: [
      "JUnit",
      "Selenium",
      "JIRA",
      "TestNG",
      "Mocha",
      "Chai",
      "Jest",
      "Postman",
      "GDB",
      "Xcode Instruments",
    ],
  },
  {
    Category: "Cloud Platforms",
    Skills: [
      "AWS",
      "Azure",
      "Google Cloud Platform",
      "Heroku",
      "Firebase",
      "IBM Cloud",
      "Alibaba Cloud",
      "DigitalOcean",
      "Oracle Cloud",
      "Salesforce",
    ],
  },
  {
    Category: "CI/CD & DevOps",
    Skills: [
      "Jenkins",
      "Travis CI",
      "CircleCI",
      "GitLab CI/CD",
      "TeamCity",
      "Bamboo",
      "Docker",
      "Kubernetes",
      "Ansible",
      "Terraform",
    ],
  },
  {
    Category: "Agile Methodologies",
    Skills: [
      "Scrum",
      "Kanban",
      "XP",
      "Lean",
      "SAFe",
      "Crystal",
      "DSDM",
      "FDD",
      "TDD",
      "ATDD",
    ],
  },
];
